function h = room(roomDim, refPoint, varargin)
% Author: Tom Shlomo, ACLab BGU, 2020



M = 100;
t = linspace(0, 1, M)';
a = roomDim(:)'.*t;
z = zeros(M,1);
l = ones(M,1).*roomDim(:)';
c = {[  a(:,1)      z       z       ]; ...
     [  a(:,1)      l(:,2)  z       ]; ...
     [  a(:,1)      z       l(:,3)  ]; ...
     [  a(:,1)      l(:,2)  l(:,3)  ]; ...
     [  z           a(:,2)  z       ];...
     [  l(:,1)      a(:,2)  z       ];...
     [  z           a(:,2)  l(:,3)  ];...
     [  l(:,1)      a(:,2)  l(:,3)  ];...
     [  z           z       a(:,3)  ];...
     [  l(:,1)      z       a(:,3)  ];...
     [  z           l(:,2)  a(:,3)  ];...
     [  l(:,1)      l(:,2)  a(:,3)  ]};
for i=1:12
    omega = c2s(c{i}-refPoint);
    omega(abs(diff(omega(:,2))) > pi/2, 2) = nan;
    h(i) = hammer.plot(omega, [], 'k-', 'LineWidth', 0.5, varargin{:});
    hold(h(i).Parent, 'on');
    hasbehavior(h(i), 'legend', false);
end